# Generated by Django 5.2.7 on 2025-10-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_video_summary_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest_date", models.DateField(auto_now_add=True)),
                ("summary_text", models.TextField(blank=True, null=True)),
                ("audio_url", models.CharField(blank=True, max_length=512, null=True)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                (
                    "videos",
                    models.ManyToManyField(related_name="digests", to="core.video"),
                ),
            ],
        ),
    ]
