# Generated by Django 5.2.7 on 2025-10-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dailydigest"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="speaker",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
